name: Java CI with Maven

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          java: [ 15 ]
      name: Java ${{ matrix.java }} compile
      steps:
        - uses: actions/checkout@master
        - name: Setup java
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}
        - run: mvn -f github-actions-java-maven/pom.xml clean compile

