name: Build Java Maven project

on: [push, pull_request]

jobs:
  start:
    runs-on: ubuntu-latest
    name: Build Java Maven project
    steps:
      - id: Start
        run: echo "Starting CI Pipeline"
  compile:
    runs-on: ubuntu-latest
    name: Java compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - run: mvn clean install
  install:
    needs: compile
    runs-on: ubuntu-latest
    name: Install
    steps:
      - run: mkdir staging && cp target/*.jar staging
