name: Build Java Maven project

on: [push, pull_request]

jobs:
  start:
    runs-on: ubuntu-latest
    name: Build Java Maven project
    steps:
      - id: Start
        run: echo "Starting CI Pipeline"
  compile:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - run: mvn -f github-actions-java-maven/pom.xml clean compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build and test project
        run: mvn -f github-actions-java-maven/pom.xml clean verify
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: github-actions-java-maven/target/github-actions-java-maven.jar